version: '3'

services:
  revproxy:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: itssoap/revproxy:0.1.0
    container_name: revproxy
    ports:
      - "8000:8000"